version: '1.0'

services:
  java-transaction:
    container_name: java-transaction
    image: softka/java-transaction
    build: .
    ports:
      - 8082:8082
    environment: 
      - DATABASE_URL=jdbc:postgresql://java_db:5432/transaccion_bd
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=root
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: transaccion_bd
    
